### ISSUE TITLE
ma progression

### ISSUE THREAD

**Issue by idetchuileng** [BioDataScience-Course/sdd-umons-2024#1]
@GuyliannEngels 

bonsoir Monsieur,
jai fait tout les h5p du module 2 mais ma progression ne mentionne pas cela. ci-joint vous avez la preuve
![progression](https://github.com/user-attachments/assets/2d257100-c3fe-4d99-8336-1ae570ca47bf)

**Comment by GuyliannEngels** [comment]
Salut @idetchuileng,

Dans la base de données, je peux voir que tu as réalisé A02Hf_git_push2 par exemple. Es-tu sûr que la capture d'écran que tu proposes est bien la dernière version actualisée de ta progression ? 

Bonne journée 
Guyliann

**Comment by idetchuileng** [comment]
Bonjour Monsieur,
Ha oui c’est un problème d’actualisation peut-être.
Merci
________________________________
De : Guyliann Engels ***@***.***>
Envoyé : jeudi 14 novembre 2024 6:54
À : BioDataScience-Course/sdd-umons-2024 ***@***.***>
Cc : IDE TCHUILENG TETOUO ***@***.***>; Mention ***@***.***>
Objet : Re: [BioDataScience-Course/sdd-umons-2024] ma progression (Issue #1)

Vous n’obtenez pas souvent d’e-mail à partir de ***@***.*** Pourquoi c’est important<https://aka.ms/LearnAboutSenderIdentification>

Salut @idetchuileng<https://github.com/idetchuileng>,

Dans la base de données, je peux voir que tu as réalisé A02Hf_git_push2 par exemple. Es-tu sûr que la capture d'écran que tu proposes est bien la dernière version actualisée de ta progression ?

Bonne journée
Guyliann

**Comment by GuyliannEngels** [comment]
Bonjour @idetchuileng,

Quand tu obtiens la réponse à une issue, il faut la clôturer (je m'en charge pour toi cette fois-ci).

Attention à bien choisir le dépôt dans lequel tu poses ta question. Tu as utilisé un dépôt public pour cette question. Je t'invite à relire la section suivante pour poser tes questions au bon endroit :

https://wp.sciviews.org/sdd-umons/?iframe=wp.sciviews.org/sdd-umons-2024/premier-projet.html

Bonne journée.

**Comment by idetchuileng** [comment]
Bonjour Guyliann,

Okey c'est compris,merci bien pour ta compréhension


________________________________
De : Guyliann Engels ***@***.***>
Envoyé : lundi 18 novembre 2024 6:41
À : BioDataScience-Course/sdd-umons-2024 ***@***.***>
Cc : IDE TCHUILENG TETOUO ***@***.***>; Mention ***@***.***>
Objet : Re: [BioDataScience-Course/sdd-umons-2024] ma progression (Issue #1)

Vous n’obtenez pas souvent d’e-mail à partir de ***@***.*** Pourquoi c’est important<https://aka.ms/LearnAboutSenderIdentification>

Bonjour @idetchuileng<https://github.com/idetchuileng>,

Quand tu obtiens la réponse à une issue, il faut la clôturer (je m'en charge pour toi cette fois-ci).

Attention à bien choisir le dépôt dans lequel tu poses ta question. Tu as utilisé un dépôt public pour cette question. Je t'invite à relire la section suivante pour poser tes questions au bon endroit :

https://wp.sciviews.org/sdd-umons/?iframe=wp.sciviews.org/sdd-umons-2024/premier-projet.html

Bonne journée.
